name: Create Release
on:
  push: {}
  repository_dispatch:
    types: generate-pr
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update dependencies
        run: npm install -g changelog-parser
      - name: find release
        id: find_version
        run: |
          VERSION=$(changelog-parser | jq ".versions[0].version" -r)
          echo "::set-output name=version::$VERSION"
      - name: Check outputs
        run: |
          echo "Version Number - ${{ steps.find_version.outputs.version }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.find_version.outputs.version }}
          release_name: Release v${{ steps.find_version.outputs.version }}
          body: |
            Release v${{ steps.find_version.outputs.version }}
          draft: false
          prerelease: false
